# Created by Jekyll Writer
title: yansicing
description: >
  jekyll based Github Pages Personal blog website ~ Learning, Summarizing,
  Sharing and Promoting
baseurl: ''
url: 'https://yansicing.github.io'
permalink: '/:year/:month/:day/:title'
repository: yansicing/yansicing.github.io
paginate: 20
github_profile: 'https://github.com/yansicing '
user: 'yansicing '
user_email: yansicing@gmail.com
markdown: kramdown

# SNS settings
RSS: false
weibo_username:     yanqincy
zhihu_username:     yansicing
github_username:    yansicing
facebook_username:  yansicing
jianshu_username:   yansicing

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
sass:
  style: compressed
future: true
